<?php

namespace ShinyBundle\Repository;

/**
 * GenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationRepository extends \Doctrine\ORM\EntityRepository{

    public function PokemonsAvailables($gen)
    {
        $qb = $this->createQueryBuilder('g')
            ->join('g.pokemons', 'p')
            ->addSelect('p')
            ->where('g.id <= :gen')
            ->setParameter('gen', $gen);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
