<?php

namespace ShinyBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPokemonFromGeneration($generation)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->where('p.generation <= :generation')
            ->setParameter('generation', $generation)
            ->orderBy('p.pokedex', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getPokemon($page, $nbPerPage)
      {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.pokedex', 'ASC');
        ;

        $query
          // On définit le début de la liste de la page
          ->setFirstResult(($page-1) * $nbPerPage)
          // Ainsi que le nombre de pokemon à afficher
          ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
      }
}
