<?php

namespace ShinyBundle\Repository;

/**
 * SpriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpriteRepository extends \Doctrine\ORM\EntityRepository
{
}
