<?php

namespace CoreBundle\Repository;

/**
 * StaticpageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticpageRepository extends \Doctrine\ORM\EntityRepository
{
}
