# src/NewsBundle/Resources/config/services.yml

services:
    sh_news.antispam:
        class: NewsBundle\Antispam\Antispam
        arguments: ['@mailer', %locale%, 50]

    sh_news.validator.antiflood:
        class: NewsBundle\Validator\AntifloodValidator
        arguments: ['@request_stack', '@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: sh_news_antiflood }    